name: Job Scheduler Overlap Checker CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Build Docker image
        run: docker build -t job-scheduler-overlap-checker .

      #- name: Push Docker image
